### ISSUE TITLE
On keyup event doesn't emit event from reactive forms valueChanges.subscribe

### ISSUE THREAD

**Issue by mchcjcols** [kekeh/angular-mydatepicker#27]
Regards reactive forms and subscribing to the valueChanges event.

The ngx-datepicker announced a valueChanges event when the user typed a date in the input text field (ie onkeyup event). The angular-mydatepicker only announces valueChanges event on the onBlur event.

**Comment by kekeh** [comment]
Hello @mchcjcols 

True but if you implement this https://github.com/kekeh/angular-mydatepicker#inputfieldchanged-callback callback you know when the value of input field changes.

Example: https://github.com/kekeh/angular-mydatepicker/wiki/inputFieldChanged-callback

Is this enough?

**Comment by kekeh** [comment]
But I have to try to fix this.

**Comment by kekeh** [comment]
Can you try this version? Let me know if it is working then I will publish this version to npm. I fixed so that now in every **keyup** the **dirty** and the **touched** values are set to **true**.

[angular-mydatepicker-0.3.9.zip](https://github.com/kekeh/angular-mydatepicker/files/4184692/angular-mydatepicker-0.3.9.zip)

How to proceed:
1. npm remove angular-mydatepicker
2. unzip the zip attachment and save it to disk
3. npm install <path_to_package>/angular-mydatepicker-0.3.9.tgz
4. ng serve

**Comment by kekeh** [comment]
I fixed this issue. Now in every **keyup** of input box  the **dirty** and the **touched** values are set to **true**.

Install the latest version **0.4.0** from npm.

**Comment by mchcjcols** [comment]
The 0.4.0 seems to work and passes my unit tests. Thank you.

**Comment by kekeh** [comment]
It is my pleasure :-)
