### ISSUE TITLE
No Option for Today button

### ISSUE THREAD

**Issue by ahavagowtham** [kekeh/angular-mydatepicker#49]
Consider adding a today button to this directive which will be more helpful.

**Comment by kekeh** [comment]
There is today footer which can be used instead of today button. Try it [here](https://kekeh.github.io/angular-mydatepicker/). At first select the **Show today footer** check box and then open the calendar.

Option name is **showFooterToday: true|false** and **todayTxt**. More info [here](https://github.com/kekeh/angular-mydatepicker#options-attribute).

**Comment by ahavagowtham** [comment]
Thank you so much.
